package com.hfr.world.earth.pack;
import java.io.*;import java.security.*;import java.util.*;import java.util.zip.*;import com.google.gson.Gson;import com.hfr.world.earth.XFEarthProfile;
public final class XFEarthMapVerifier {
 public static final int MAX_ENTRIES=1000000,MAX_PATH=512; public static final long MAX_FILE=8L*1024*1024*1024,MAX_TOTAL=128L*1024*1024*1024;
 private static final Set<String> FORBIDDEN=new HashSet<String>(Arrays.asList("session.lock","level.dat_old","uid.dat"));
 private XFEarthMapVerifier(){}
 public static String sanitizePath(String raw){if(raw==null||raw.length()==0||raw.length()>MAX_PATH||raw.indexOf('\0')>=0)bad("invalid path");String p=raw.replace('\\','/');if(p.startsWith("/")||p.startsWith("//")||p.matches("^[A-Za-z]:.*"))bad("absolute path: "+raw);StringBuilder out=new StringBuilder();for(String part:p.split("/")){if(part.length()==0||".".equals(part))continue;if("..".equals(part))bad("traversal: "+raw);if(out.length()>0)out.append('/');out.append(part);}p=out.toString();String low=p.toLowerCase(Locale.ROOT);String top=low.contains("/")?low.substring(0,low.indexOf('/')):low;if(FORBIDDEN.contains(low)||Arrays.asList("playerdata","players","stats","advancements","crash-reports","logs").contains(top))bad("forbidden save data: "+raw);if(low.matches(".*\\.(exe|dll|so|dylib|bat|cmd|com|scr|jar|class|ps1|sh)$"))bad("executable entry: "+raw);return p;}
 public static XFEarthMapManifest verify(File archive)throws IOException{return verify(archive,null);}
 public static XFEarthMapManifest verify(File archive,String expectedArchiveHash)throws IOException{if(expectedArchiveHash!=null&&!expectedArchiveHash.equalsIgnoreCase(sha256(archive)))throw new IOException("Earth map archive SHA-256 mismatch");ZipFile zip=new ZipFile(archive);try{if(zip.size()>MAX_ENTRIES)throw new IOException("Archive entry limit exceeded");Set<String> names=new HashSet<String>();ZipEntry me=zip.getEntry("earth-map-pack.json");if(me==null)throw new IOException("Missing earth-map-pack.json");XFEarthMapManifest m=readJson(zip,me,XFEarthMapManifest.class);m.validate();long total=0;Enumeration<? extends ZipEntry> es=zip.entries();while(es.hasMoreElements()){ZipEntry e=es.nextElement();String p=sanitizePath(e.getName());if(!names.add(p))throw new IOException("Duplicate normalized path: "+p);if(!e.isDirectory()){long n=count(zip.getInputStream(e),null);if(n>MAX_FILE)throw new IOException("Entry size limit exceeded: "+p);total+=n;if(total>MAX_TOTAL)throw new IOException("Total extraction limit exceeded");}}Map<String,XFEarthMapManifest.FileEntry> listed=new HashMap<String,XFEarthMapManifest.FileEntry>();for(XFEarthMapManifest.FileEntry f:m.files)listed.put(sanitizePath(f.path),f);for(XFEarthMapManifest.FileEntry f:m.files){ZipEntry e=zip.getEntry(f.path);if(e==null)throw new IOException("Manifest file missing: "+f.path);MessageDigest d=digest();long n=count(zip.getInputStream(e),d);if(n!=f.size)throw new IOException("Size mismatch: "+f.path);if(!hex(d.digest()).equalsIgnoreCase(f.sha256))throw new IOException("SHA-256 mismatch: "+f.path);}ZipEntry pe=zip.getEntry("xenoearth-profile.json");if(pe==null||zip.getEntry("template-level.dat")==null)throw new IOException("Profile or template-level.dat missing");XFEarthProfile profile=readJson(zip,pe,XFEarthProfile.class);profile.validateForPack(m);return m;}finally{zip.close();}}
 private static <T>T readJson(ZipFile z,ZipEntry e,Class<T> c)throws IOException{Reader r=new InputStreamReader(z.getInputStream(e),"UTF-8");try{return new Gson().fromJson(r,c);}finally{r.close();}}
 static long count(InputStream in,MessageDigest d)throws IOException{try{byte[]b=new byte[65536];long n=0;for(int x;(x=in.read(b))!=-1;){n+=x;if(n>MAX_FILE)throw new IOException("Entry size limit exceeded");if(d!=null)d.update(b,0,x);}return n;}finally{in.close();}}
 public static String sha256(File f)throws IOException{InputStream in=new FileInputStream(f);MessageDigest d=digest();count(in,d);return hex(d.digest());} private static MessageDigest digest(){try{return MessageDigest.getInstance("SHA-256");}catch(Exception e){throw new AssertionError(e);}} private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x&255));return s.toString();} private static void bad(String m){throw new IllegalArgumentException("Unsafe Earth map path: "+m);}
}
