package com.hfr.world.earth.pack;
import java.io.*;import java.util.*;import java.util.zip.*;import com.google.gson.Gson;import net.minecraft.nbt.*;
public final class XFEarthMapInstaller {
 public interface Cancellation { boolean cancelled(); } public interface Progress { void update(String stage,String file,long files,long totalFiles,long bytes,long totalBytes); }
 public static final class Settings {public String levelName,generatorOptions;public long seed;public int gameType;public boolean hardcore,structures,commands,bonusChest;}
 public File install(File archive,XFEarthMapPack pack,File saves,String folder,Settings settings,Cancellation cancel,Progress progress)throws IOException{
  File target=new File(saves,folder),temp=new File(saves,folder+".xfearth-installing");if(target.exists())throw new IOException("Existing save will not be overwritten: "+target);if(temp.exists()){File marker=new File(temp,".xfearth-partial");if(!marker.isFile())throw new IOException("Temporary directory exists and is not a proven Earth partial install: "+temp);delete(temp);}if(!temp.mkdirs())throw new IOException("Cannot create temporary save");new File(temp,".xfearth-partial").createNewFile();boolean ok=false;try{XFEarthMapManifest m=XFEarthMapVerifier.verify(archive,pack.archiveSha256);check(cancel);extract(archive,temp,m,cancel,progress);patchLevel(new File(temp,"template-level.dat"),new File(temp,"level.dat"),settings);new File(temp,"template-level.dat").delete();writeInstall(temp,pack);new File(temp,".xfearth-partial").delete();if(!temp.renameTo(target))throw new IOException("Could not atomically finalize Earth save");ok=true;return target;}finally{if(!ok)delete(temp);}}
 private static void extract(File archive,File root,XFEarthMapManifest m,Cancellation c,Progress p)throws IOException{ZipFile z=new ZipFile(archive);long done=0;int files=0;try{Enumeration<? extends ZipEntry> es=z.entries();while(es.hasMoreElements()){check(c);ZipEntry e=es.nextElement();String path=XFEarthMapVerifier.sanitizePath(e.getName());if("earth-map-pack.json".equals(path))continue;File out=new File(root,path);String base=root.getCanonicalPath()+File.separator;if(!out.getCanonicalPath().startsWith(base))throw new IOException("Archive escaped destination");if(e.isDirectory()){out.mkdirs();continue;}out.getParentFile().mkdirs();InputStream in=z.getInputStream(e);OutputStream os=new FileOutputStream(out);try{byte[]b=new byte[65536];long entry=0;for(int n;(n=in.read(b))!=-1;){check(c);entry+=n;done+=n;if(entry>XFEarthMapVerifier.MAX_FILE||done>XFEarthMapVerifier.MAX_TOTAL)throw new IOException("Extraction size limit exceeded");os.write(b,0,n);}}finally{try{in.close();}finally{os.close();}}files++;if(p!=null)p.update("Extracting map data",path,files,m.files.size(),done,m.installedSize);}}finally{z.close();}}
 public static void patchLevel(File template,File output,Settings s)throws IOException{NBTTagCompound root=CompressedStreamTools.readCompressed(new FileInputStream(template));NBTTagCompound d=root.getCompoundTag("Data");d.removeTag("Player");d.setString("LevelName",s.levelName);d.setLong("RandomSeed",s.seed);d.setInteger("GameType",s.gameType);d.setBoolean("hardcore",s.hardcore);d.setBoolean("allowCommands",s.commands);d.setBoolean("MapFeatures",s.structures);d.setString("generatorName","earthmap");d.setInteger("generatorVersion",0);d.setString("generatorOptions",s.generatorOptions);d.setBoolean("bonusChest",s.bonusChest);d.setLong("Time",0);d.setLong("DayTime",0);d.setBoolean("raining",false);d.setBoolean("thundering",false);d.setInteger("rainTime",0);d.setInteger("thunderTime",0);d.setLong("LastPlayed",System.currentTimeMillis());d.setLong("SizeOnDisk",0);File tmp=new File(output.getPath()+".tmp");FileOutputStream out=new FileOutputStream(tmp);try{CompressedStreamTools.writeCompressed(root,out);}finally{out.close();}if(output.exists()&&!output.delete())throw new IOException("Cannot replace level.dat");if(!tmp.renameTo(output))throw new IOException("Cannot atomically write level.dat");}
 private static void writeInstall(File root,XFEarthMapPack p)throws IOException{Map<String,Object> x=new LinkedHashMap<String,Object>();x.put("formatVersion",1);x.put("packId",p.manifest.id);x.put("packVersion",p.manifest.version);x.put("archiveSha256",p.archiveSha256);x.put("installedAt",System.currentTimeMillis());x.put("populationMode",p.manifest.populationMode);Writer w=new OutputStreamWriter(new FileOutputStream(new File(root,"xfearth-install.json")),"UTF-8");try{new Gson().toJson(x,w);}finally{w.close();}}
 private static void check(Cancellation c)throws IOException{if(c!=null&&c.cancelled())throw new InterruptedIOException("Earth installation cancelled");}private static void delete(File f)throws IOException{if(!f.exists())return;if(f.isDirectory()){File[]cs=f.listFiles();if(cs!=null)for(File c:cs)delete(c);}if(!f.delete())throw new IOException("Cannot remove "+f);}
}
