package com.hfr.client.earth;
import java.io.*;import net.minecraft.client.gui.*;import cpw.mods.fml.relauncher.*;import com.hfr.world.earth.pack.*;
@SideOnly(Side.CLIENT) public final class GuiXFEarthInstall extends GuiScreen implements XFEarthMapInstaller.Progress,XFEarthMapInstaller.Cancellation {
 private final GuiCreateWorld parent;private final PendingEarthWorldCreation pending;private volatile boolean cancel;private volatile String stage="Locating map pack",file="";private volatile long files,totalFiles,bytes,totalBytes;private volatile String error;
 public GuiXFEarthInstall(GuiCreateWorld parent,PendingEarthWorldCreation p){this.parent=parent;pending=p;}
 public void initGui(){buttonList.add(new GuiButton(0,width/2-100,height-35,200,20,"Cancel"));Thread worker=new Thread(new Runnable(){public void run(){install();}},"XF Earth map installer");worker.setDaemon(true);worker.start();}
 private void install(){try{XFEarthMapRepository repo=new XFEarthMapRepository(mc.mcDataDir);XFEarthMapPack pack=repo.find(pending.packId);if(pack==null)throw new IOException("Selected map pack is not installed or bundled: "+pending.packId);java.util.List<String> missing=pack.missingMods();if(!missing.isEmpty())throw new IOException("Missing required content mods: "+missing);stage="Verifying archive";File archive=repo.materialize(pack);File saves=new File(mc.mcDataDir,"saves");new XFEarthMapInstaller().install(archive,pack,saves,pending.folderName,pending.settings(),this,this);stage="Launching world";mc.func_152344_a(new Runnable(){public void run(){mc.launchIntegratedServer(pending.folderName,pending.displayName,null);}});}catch(final Exception e){error=e.getMessage();}}
 protected void actionPerformed(GuiButton b){cancel=true;if(error!=null)mc.displayGuiScreen(parent);}
 public boolean cancelled(){return cancel;}public void update(String s,String f,long n,long t,long b,long tb){stage=s;file=f;files=n;totalFiles=t;bytes=b;totalBytes=tb;}
 public void drawScreen(int x,int y,float f){drawDefaultBackground();drawCenteredString(fontRendererObj,"Installing "+pending.packId,width/2,25,0xffffff);drawCenteredString(fontRendererObj,error==null?stage:"Installation failed: "+error,width/2,55,error==null?0xffffff:0xff5555);drawCenteredString(fontRendererObj,file,width/2,75,0xaaaaaa);drawCenteredString(fontRendererObj,"Files "+files+" / "+totalFiles+"   Bytes "+bytes+" / "+totalBytes,width/2,95,0xffffff);long pct=totalBytes<=0?0:Math.min(100,bytes*100/totalBytes);drawCenteredString(fontRendererObj,pct+"%",width/2,115,0xffffff);super.drawScreen(x,y,f);}
}
