package com.hfr.client.earth;
import java.lang.reflect.Field;import java.util.*;import net.minecraft.client.gui.*;import cpw.mods.fml.relauncher.*;import cpw.mods.fml.relauncher.ReflectionHelper;import com.hfr.world.earth.pack.*;
@SideOnly(Side.CLIENT) public final class GuiXFEarthCustomize extends GuiScreen {
 private final GuiCreateWorld parent;private final String[] ids={XFEarthMapRepository.CLEAN,XFEarthMapRepository.POPULATED,"external"};private int selected;
 public GuiXFEarthCustomize(GuiCreateWorld parent){this.parent=parent;String current=PendingEarthWorldCreation.packId(readOptions(parent));for(int i=0;i<ids.length;i++)if(ids[i].equals(current))selected=i;}
 public void initGui(){buttonList.clear();buttonList.add(new GuiButton(10,width/2-155,height-32,150,20,"Select"));buttonList.add(new GuiButton(11,width/2+5,height-32,150,20,"Cancel"));for(int i=0;i<3;i++)buttonList.add(new GuiButton(i,width/2-155,45+i*24,310,20,title(i)));}
 protected void actionPerformed(GuiButton b){if(b.id>=0&&b.id<3){selected=b.id;return;}if(b.id==10){if(selected<2)writeOptions(parent,PendingEarthWorldCreation.options(ids[selected]));mc.displayGuiScreen(parent);}if(b.id==11)mc.displayGuiScreen(parent);}
 private String title(int i){String n=i==0?"Earth 1:16000 — Clean":i==1?"Earth 1:16000 — Populated":"External Earth Map Pack";return (i==selected?"> ":"")+n;}
 public void drawScreen(int mx,int my,float tick){drawDefaultBackground();drawCenteredString(fontRendererObj,"Select an Earth map variant",width/2,18,0xffffff);String[] lines=selected==0?new String[]{"Scale 1:16000 | 2688 x 1344 | clean-pregenerated","Lightweight Earth map with solid underground stone and no Minecraft population.","Recommended for Xenofactions custom stone-drop systems."}:selected==1?new String[]{"Scale 1:16000 | 2688 x 1344 | already populated | HEAVIER","Modpack-dependent: ores, pools, deposits and compatible mod plants.","Requires every content mod used when the template was created."}:new String[]{"Local/external .xfmap under xenofactions/earthmaps","Intended for future large packs such as Earth 1:1000.","No automatic Internet download is performed."};int y=130;for(String s:lines){drawCenteredString(fontRendererObj,s,width/2,y,0xdddddd);y+=13;}super.drawScreen(mx,my,tick);}
 static String readOptions(GuiCreateWorld g){try{return ReflectionHelper.getPrivateValue(GuiCreateWorld.class,g,"field_146334_a");}catch(Exception e){return "";}}
 static void writeOptions(GuiCreateWorld g,String v){try{ReflectionHelper.setPrivateValue(GuiCreateWorld.class,g,v,"field_146334_a");}catch(Exception e){throw new IllegalStateException("Cannot set Forge 1.7.10 generator options field field_146334_a",e);}}
}
