gtnh.settings.blowdryerTag = 0.2.2
gtnh.modules.codeStyle = false
modName = Xenofactions
modId = hfr
modGroup = com.hfr
modVersion = 2.2.4
useModGroupForPublishing = true
customArchiveBaseName = Xenofactions
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
enableModernJavaSyntax = false
enableGenericInjection = true
generateGradleTokenClass =
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
earthCleanMap =
earthPopulatedMap =
includeBundledEarthMaps = false
forceEnableMixins = false
usesShadowedDependencies = false
includeWellKnownRepositories = true
usesMavenPublishing = false
runDir = eclipse
developmentEnvironmentUserName =
