package com.hfr.packet.builder;
import com.hfr.builder.*;import com.hfr.schematic.*;import com.hfr.tileentity.machine.TileEntityMachineBuilder;import cpw.mods.fml.common.network.ByteBufUtils;import cpw.mods.fml.common.network.simpleimpl.*;import io.netty.buffer.ByteBuf;import net.minecraft.entity.player.EntityPlayerMP;import net.minecraft.tileentity.TileEntity;
/** Validated client intent for changing the persistent Depot draft. */
public class BuilderPlanPacket implements IMessage{
 public int dimension,x,y,z,originX,originY,originZ,rotation;public boolean mirrored,preview,clear;public String source="",schematicId="";
 public BuilderPlanPacket(){}public BuilderPlanPacket(TileEntityMachineBuilder d,String source,String id,int ox,int oy,int oz,int r,boolean m,boolean p){dimension=d.getWorldObj().provider.dimensionId;x=d.xCoord;y=d.yCoord;z=d.zCoord;this.source=source;schematicId=id;originX=ox;originY=oy;originZ=oz;rotation=r;mirrored=m;preview=p;}
 public void fromBytes(ByteBuf b){dimension=b.readInt();x=b.readInt();y=b.readInt();z=b.readInt();originX=b.readInt();originY=b.readInt();originZ=b.readInt();rotation=b.readByte();mirrored=b.readBoolean();preview=b.readBoolean();clear=b.readBoolean();source=ByteBufUtils.readUTF8String(b);schematicId=ByteBufUtils.readUTF8String(b);}public void toBytes(ByteBuf b){b.writeInt(dimension);b.writeInt(x);b.writeInt(y);b.writeInt(z);b.writeInt(originX);b.writeInt(originY);b.writeInt(originZ);b.writeByte(rotation);b.writeBoolean(mirrored);b.writeBoolean(preview);b.writeBoolean(clear);ByteBufUtils.writeUTF8String(b,source);ByteBufUtils.writeUTF8String(b,schematicId);}
 public static class Handler implements IMessageHandler<BuilderPlanPacket,IMessage>{public IMessage onMessage(BuilderPlanPacket m,MessageContext c){EntityPlayerMP p=c.getServerHandler().playerEntity;if(p==null||p.dimension!=m.dimension||p.getDistanceSq(m.x+.5,m.y+.5,m.z+.5)>64)return null;TileEntity te=p.worldObj.getTileEntity(m.x,m.y,m.z);if(!(te instanceof TileEntityMachineBuilder))return null;TileEntityMachineBuilder d=(TileEntityMachineBuilder)te;if(!BuilderDepotService.mayBuild(p,d))return null;BuilderPlan plan=d.getPlan();if(m.clear){plan.clear("gui.builder.validation.no_schematic");d.planChanged();return BuilderDepotSnapshotPacket.create(d);}if(m.rotation<0||m.rotation>3||m.originY<0||m.originY>=p.worldObj.getHeight()||Math.abs((long)m.originX)>30000000L||Math.abs((long)m.originZ)>30000000L)return null;Schematic s=null;if(BuilderPlan.NATIVE.equals(m.source))s=SchematicLibrary.get().resolve(m.schematicId);else if(BuilderPlan.STORED.equals(m.source)){SchematicStoreData store=SchematicStoreData.get(p.worldObj);s=store==null?null:store.getSchematic(m.schematicId);}if(s==null){plan.clear("gui.builder.validation.schematic_missing");d.planChanged();return BuilderDepotSnapshotPacket.create(d);}plan.source=m.source;plan.schematicId=m.schematicId;plan.displayName=s.name;plan.originX=m.originX;plan.originY=m.originY;plan.originZ=m.originZ;plan.rotation=m.rotation;plan.mirrored=m.mirrored;plan.preview=m.preview;plan.validationKey="gui.builder.validation.not_run";d.planChanged();return BuilderDepotSnapshotPacket.create(d);}}
}
