package com.hfr.inventory.gui;

import java.util.*;
import org.lwjgl.input.Keyboard;
import org.lwjgl.opengl.GL11;
import com.hfr.builder.BuilderMaterialResolver;
import com.hfr.inventory.container.ContainerMachineBuilder;
import com.hfr.packet.PacketDispatcher;
import com.hfr.packet.builder.*;
import com.hfr.schematic.Schematic;
import com.hfr.tileentity.machine.TileEntityMachineBuilder;
import net.minecraft.client.gui.*;
import net.minecraft.client.gui.inventory.GuiContainer;
import net.minecraft.client.resources.I18n;
import net.minecraft.entity.player.InventoryPlayer;
import net.minecraft.item.ItemStack;

/** Builder Depot planning, material inventory, and queue management screen. */
public class GUIMachineBuilder extends GuiContainer {
    private static final int TAB_FIRST=100,SELECT=10,ROTATE=11,MIRROR=12,PREVIEW=13,CLEAR=14,VALIDATE=15,START=16,RECALL=20,PAUSE=21,RESUME=22,CANCEL=23;
    private final TileEntityMachineBuilder depot;private final ContainerMachineBuilder container;private int page,rotation;private boolean mirror;private GuiTextField fx,fy,fz;private String message="",validation="gui.builder.validation.not_run";private Schematic selectedSchematic;private BuilderLibraryPacket.Entry selectedNative;private final List<String> materialLines=new ArrayList<String>();
    public GUIMachineBuilder(InventoryPlayer player,TileEntityMachineBuilder depot){super(new ContainerMachineBuilder(player,depot));this.container=(ContainerMachineBuilder)inventorySlots;this.depot=depot;xSize=370;ySize=226;}
    @Override public void initGui(){super.initGui();Keyboard.enableRepeatEvents(true);if(fx==null){fx=field(96,depot.xCoord+2);fy=field(118,depot.yCoord);fz=field(140,depot.zCoord+2);}else repositionFields();rebuildButtons();request();}
    private GuiTextField field(int y,int value){GuiTextField f=new GuiTextField(fontRendererObj,guiLeft+235,guiTop+y,68,18);f.setText(String.valueOf(value));return f;}
    private void repositionFields(){fx.xPosition=fy.xPosition=fz.xPosition=guiLeft+235;fx.yPosition=guiTop+96;fy.yPosition=guiTop+118;fz.yPosition=guiTop+140;}
    private String tr(String key,Object...args){return I18n.format(key,args);}
    private void request(){PacketDispatcher.wrapper.sendToServer(new BuilderDepotRequestPacket(mc.thePlayer.dimension,depot.xCoord,depot.yCoord,depot.zCoord));}
    @Override public void onGuiClosed(){Keyboard.enableRepeatEvents(false);super.onGuiClosed();}
    @Override public void updateScreen(){super.updateScreen();if(page==1){fx.updateCursorCounter();fy.updateCursorCounter();fz.updateCursorCounter();}if(mc.thePlayer.ticksExisted%20==0){request();rebuildButtons();}}
    private void rebuildButtons(){buttonList.clear();for(int i=0;i<4;i++)buttonList.add(new GuiButton(TAB_FIRST+i,guiLeft+8+i*88,guiTop+7,84,20,tr("gui.builder.tab."+i)));container.setMaterialsVisible(page==2);
        BuilderDepotSnapshotPacket s=snapshot();if(page==0){add(RECALL,10,180,76,"gui.builder.recall",s!=null&&!s.builderId.isEmpty());add(PAUSE,90,180,70,"gui.builder.pause",s!=null&&s.total>0&&!"PAUSED".equals(s.state));add(RESUME,164,180,70,"gui.builder.resume",s!=null&&"PAUSED".equals(s.state));add(CANCEL,238,180,92,"gui.builder.cancel",s!=null&&s.total>0);}
        else if(page==1){add(SELECT,10,50,142,"gui.builder.select",true);add(ROTATE,235,164,65,"gui.builder.rotate",(selectedSchematic!=null||selectedNative!=null));add(MIRROR,304,164,56,"gui.builder.mirror",(selectedSchematic!=null||selectedNative!=null));add(PREVIEW,10,190,70,"gui.builder.preview",selectedSchematic!=null);add(CLEAR,84,190,82,"gui.builder.clear_preview",depot.preview!=null);add(VALIDATE,170,190,70,"gui.builder.validate",selectedSchematic!=null||selectedNative!=null);add(START,244,190,116,"gui.builder.start",(selectedSchematic!=null||selectedNative!=null)&&validation.startsWith("gui.builder.validation.valid"));}
        else if(page==3&&s!=null){for(int i=0;i<s.queue.size()&&i<6;i++){int y=82+i*22;add(300+i*3,225,y,42,"gui.builder.up",i>0);add(301+i*3,271,y,42,"gui.builder.down",i+1<s.queue.size());add(302+i*3,317,y,43,"gui.builder.remove",true);}}
    }
    private void add(int id,int x,int y,int w,String key,boolean enabled){GuiButton b=new GuiButton(id,guiLeft+x,guiTop+y,w,20,tr(key));b.enabled=enabled;buttonList.add(b);}
    @Override protected void actionPerformed(GuiButton b){if(!b.enabled)return;if(b.id>=TAB_FIRST&&b.id<TAB_FIRST+4){page=b.id-TAB_FIRST;if(page==2)cacheMaterials();rebuildButtons();return;}switch(b.id){case RECALL:action(BuilderActionPacket.RECALL);break;case PAUSE:action(BuilderActionPacket.PAUSE);break;case RESUME:action(BuilderActionPacket.RESUME);break;case CANCEL:action(BuilderActionPacket.CANCEL);break;case SELECT:mc.displayGuiScreen(new GUIBuilderSchematicSelection(this));return;case ROTATE:rotation=(rotation+1)&3;validation="gui.builder.validation.not_run";break;case MIRROR:mirror=!mirror;validation="gui.builder.validation.not_run";break;case PREVIEW:preview();break;case CLEAR:depot.preview=null;message=tr("gui.builder.preview.cleared");break;case VALIDATE:validation=validateClient();message=tr(validation);break;case START:start();break;default:if(b.id>=300){int i=(b.id-300)/3,op=(b.id-300)%3;indexed(op==0?BuilderActionPacket.UP:op==1?BuilderActionPacket.DOWN:BuilderActionPacket.REMOVE,i);}}rebuildButtons();request();}
    public BuilderLibraryPacket.Entry getNativeSelection(){return selectedNative;} public Schematic getImportedSelection(){return selectedNative==null?selectedSchematic:null;} public int getDepotX(){return depot.xCoord;} public int getDepotY(){return depot.yCoord;} public int getDepotZ(){return depot.zCoord;}
    public void selectImportedSchematic(Schematic s){selectedNative=null;selectedSchematic=s;validation="gui.builder.validation.not_run";cacheMaterials();rebuildButtons();}
    public void selectNativeSchematic(BuilderLibraryPacket.Entry e){selectedNative=e;selectedSchematic=null;validation="gui.builder.validation.not_run";materialLines.clear();rebuildButtons();}
    @Override protected void drawGuiContainerBackgroundLayer(float partial,int mx,int my){GL11.glDisable(GL11.GL_LIGHTING);drawRect(guiLeft,guiTop,guiLeft+xSize,guiTop+ySize,0xff18222d);drawRect(guiLeft+6,guiTop+32,guiLeft+xSize-6,guiTop+ySize-6,0xff263746);if(page==2){drawRect(guiLeft+10,guiTop+69,guiLeft+176,guiTop+216,0xff8b8b8b);}}
    @Override protected void drawGuiContainerForegroundLayer(int mx,int my){BuilderDepotSnapshotPacket s=snapshot();title("gui.builder.depot",42);if(page==0)overview(s);else if(page==1)build();else if(page==2)materials();else queue(s);if(!message.isEmpty())fontRendererObj.drawSplitString(message,10,211,350,0xffdddd77);}
    private BuilderDepotSnapshotPacket snapshot(){return BuilderDepotSnapshotPacket.get(mc.thePlayer.dimension,depot.xCoord,depot.yCoord,depot.zCoord);}
    private void overview(BuilderDepotSnapshotPacket s){if(s==null){line(tr("gui.builder.loading"),58);return;}line(tr("gui.builder.builder",empty(s.builderName)),58);line(tr("gui.builder.faction",empty(s.faction)),72);line(tr("gui.builder.city",empty(s.city)),86);line(tr("gui.builder.status",state(s.state)),100);line(tr("gui.builder.current",empty(s.schematic)),114);int percent=s.total<=0?0:(int)(100L*s.progress/s.total);line(tr("gui.builder.progress",s.progress,s.total,percent),128);drawRect(10,144,350,158,0xff111111);drawRect(11,145,11+(338*percent/100),157,0xff55aa66);if(s.blocked)line(tr("gui.builder.blocked",s.bx,s.by,s.bz),164);}
    private void build(){line(tr("gui.builder.workflow.select"),76);line(tr("gui.builder.selected",selectedNative!=null?selectedNative.name:selectedSchematic==null?tr("gui.builder.none"):selectedSchematic.name),62,76);line(tr("gui.builder.workflow.position"),86);line("X",215,100);line("Y",215,122);line("Z",215,144);fx.drawTextBox();fy.drawTextBox();fz.drawTextBox();if(selectedNative!=null)line(tr("gui.builder.dimensions",selectedNative.width,selectedNative.height,selectedNative.length),62,90);else if(selectedSchematic!=null)line(tr("gui.builder.dimensions",selectedSchematic.width,selectedSchematic.height,selectedSchematic.length),62,90);line(tr("gui.builder.rotation",rotation*90),62,108);line(tr("gui.builder.mirror_state",mirror?tr("gui.builder.yes"):tr("gui.builder.no")),62,122);line(tr("gui.builder.workflow.preview"),10,138);line(tr("gui.builder.workflow.validate"),10,152);line(tr("gui.builder.workflow.start"),10,166);line(tr("gui.builder.validation",tr(validation)),170,76);}
    private void materials(){line(tr("gui.builder.materials.depot"),50);line(tr("gui.builder.materials.player"),122);line(tr("gui.builder.materials.required"),190,50);int y=66;for(String value:materialLines){fontRendererObj.drawSplitString(value,190,y,168,0xffffff);y+=20;if(y>200)break;}if(materialLines.isEmpty())line(tr("gui.builder.materials.empty"),190,68);}
    private void queue(BuilderDepotSnapshotPacket s){if(s==null){line(tr("gui.builder.loading"),58);return;}line(tr("gui.builder.queue.active"),54);line(empty(s.schematic)+" | "+state(s.state)+" | "+s.progress+"/"+s.total,68);line(tr("gui.builder.queue.queued"),90);int y=88;for(int i=0;i<s.queue.size()&&i<6;i++){line((i+1)+". "+s.queue.get(i),10,y+7);y+=22;}}
    private void cacheMaterials(){materialLines.clear();if(selectedSchematic==null)return;Map<String,Integer> required=new LinkedHashMap<String,Integer>(),stored=new HashMap<String,Integer>();for(int i=1;i<=27;i++){ItemStack a=depot.getStackInSlot(i);if(a!=null)stored.put(a.getDisplayName(),(stored.containsKey(a.getDisplayName())?stored.get(a.getDisplayName()):0)+a.stackSize);}for(int x=0;x<selectedSchematic.width;x++)for(int y=0;y<selectedSchematic.height;y++)for(int z=0;z<selectedSchematic.length;z++){ItemStack a=BuilderMaterialResolver.resolve(selectedSchematic.resolveBlock(x,y,z),selectedSchematic.getMetadata(x,y,z));String k=a==null?tr("gui.builder.unsupported"):a.getDisplayName();required.put(k,(required.containsKey(k)?required.get(k):0)+1);}for(Map.Entry<String,Integer> e:required.entrySet()){int have=stored.containsKey(e.getKey())?stored.get(e.getKey()):0,remaining=Math.max(0,e.getValue()-have);materialLines.add(tr("gui.builder.material.line",e.getKey(),e.getValue(),have,remaining,remaining>0?tr("gui.builder.missing"):tr("gui.builder.complete")));}}
    private void preview(){String v=validateClient();validation=v;if(!v.startsWith("gui.builder.validation.valid")){message=tr(v);return;}depot.preview=selectedSchematic;depot.previewX=num(fx);depot.previewY=num(fy);depot.previewZ=num(fz);depot.previewRotation=rotation;depot.previewMirrored=mirror;message=tr("gui.builder.preview.enabled");}
    private String validateClient(){if(selectedSchematic==null&&selectedNative==null)return "gui.builder.validation.no_schematic";try{num(fx);num(fy);num(fz);}catch(Exception e){return "gui.builder.validation.coordinates";}return "gui.builder.validation.valid";}
    private void start(){String v=validateClient();validation=v;if(!v.startsWith("gui.builder.validation.valid")){message=tr(v);return;}if(selectedNative!=null){BuilderActionPacket p=new BuilderActionPacket(depot,BuilderActionPacket.START);p.a=num(fx);p.b=num(fy);p.c=num(fz);p.rotation=rotation;p.mirror=mirror;p.schematic=selectedNative.id;PacketDispatcher.wrapper.sendToServer(p);}else PacketDispatcher.wrapper.sendToServer(new BuilderSchematicPacket(depot,selectedSchematic,num(fx),num(fy),num(fz),rotation,mirror));message=tr("gui.builder.request.sent");}
    private int num(GuiTextField f){return Integer.parseInt(f.getText());}private void action(int a){PacketDispatcher.wrapper.sendToServer(new BuilderActionPacket(depot,a));}private void indexed(int a,int i){BuilderActionPacket p=new BuilderActionPacket(depot,a);p.a=i;PacketDispatcher.wrapper.sendToServer(p);}private void title(String k,int y){line(tr(k),10,y);}private void line(String s,int y){line(s,10,y);}private void line(String s,int x,int y){fontRendererObj.drawString(s,x,y,0xffffff);}private String empty(String s){return s==null||s.isEmpty()?tr("gui.builder.none"):s;}private String state(String s){return tr("builder.state."+(s==null?"IDLE":s));}
    @Override protected void mouseClicked(int mx,int my,int button){super.mouseClicked(mx,my,button);if(page==1){fx.mouseClicked(mx,my,button);fy.mouseClicked(mx,my,button);fz.mouseClicked(mx,my,button);}}
    @Override protected void keyTyped(char c,int key){if(page==1&&(fx.textboxKeyTyped(c,key)||fy.textboxKeyTyped(c,key)||fz.textboxKeyTyped(c,key))){validation="gui.builder.validation.not_run";rebuildButtons();return;}super.keyTyped(c,key);}
}
