package com.hfr.builder;

public enum BuilderState {
	IDLE, LOAD_JOB, VALIDATE_JOB, FIND_NEXT_BLOCK, MOVE_TO_SITE, GETTING_MATERIALS,
	BREAKING_BLOCK, PLACING_BLOCK, WAITING_FOR_MATERIALS, BUILDER_INVENTORY_FULL, WAITING_FOR_CHUNK,
	PATHFINDING_ERROR, INVALID_TERRITORY, UNSUPPORTED_BLOCK, PAUSED, COMPLETE
}
