package com.hfr.command;
import java.io.File; import com.hfr.config.XFConfig; import com.hfr.world.earth.*; import com.hfr.world.earth.pack.*;
import net.minecraft.command.*; import net.minecraft.server.MinecraftServer; import net.minecraft.util.ChatComponentText; import net.minecraft.world.WorldServer;
public final class EarthCommandHandler {
 private EarthCommandHandler(){}
 public static final String USAGE="/xc earth status | packs | verify <pack-id> | check <chunkX> <chunkZ>";
 public static void execute(ICommandSender s,String[] a){WorldServer w=MinecraftServer.getServer().worldServerForDimension(0);File root=w.getSaveHandler().getWorldDirectory();XFEarthProfile p=null;try{if(XFEarthProfileLoader.exists(root))p=XFEarthProfileLoader.load(root);}catch(Exception e){msg(s,"Profile error: "+e.getMessage());}
  if(a.length==1&&"packs".equalsIgnoreCase(a[0])){java.util.List<XFEarthMapPack> packs=new XFEarthMapRepository(new File(".")).discover();msg(s,"Available Earth map packs: "+packs.size());for(XFEarthMapPack pack:packs)msg(s,pack.manifest.id+" "+pack.manifest.version+" ["+pack.source.getProvider()+"] "+(pack.isCompatible()?"compatible":"missing mods "+pack.missingMods()));return;}
  if(a.length==2&&"verify".equalsIgnoreCase(a[0])){XFEarthMapRepository repo=new XFEarthMapRepository(new File("."));XFEarthMapPack pack=repo.find(a[1]);if(pack==null)throw new CommandException("Unknown or unavailable Earth pack: "+a[1]);try{XFEarthMapVerifier.verify(repo.materialize(pack),pack.archiveSha256);msg(s,"Verified "+pack.manifest.id+" archive SHA-256 "+pack.archiveSha256);}catch(Exception e){throw new CommandException("Verification failed: "+e.getMessage());}return;}
  if(a.length==1&&"status".equalsIgnoreCase(a[0])){msg(s,"Earth world type registered: "+XFEarthRegistry.isRegistered());msg(s,"Current overworld terrain type: "+w.getWorldInfo().getTerrainType().getWorldTypeName());msg(s,"Profile path: "+XFEarthProfileLoader.path(root)); if(p!=null){msg(s,"Profile name: "+p.getProfile());msg(s,"Effective scale: "+p.getEffectiveScale());msg(s,"Block bounds: "+p.getBounds().blockString());msg(s,"Chunk bounds: "+p.getBounds().chunkString());msg(s,"Sea level: "+p.getSeaLevel());}msg(s,"Missing chunk policy: "+XFConfig.earthMissingChunkPolicy);msg(s,"Boundary mode: "+XFConfig.earthBoundaryMode);msg(s,"Correctly adopted: "+(XFEarthRegistry.get()!=null&&w.getWorldInfo().getTerrainType()==XFEarthRegistry.get()&&p!=null));return;}
  if(a.length==3&&"check".equalsIgnoreCase(a[0])){int x=CommandBase.parseInt(s,a[1]),z=CommandBase.parseInt(s,a[2]);boolean inside=p!=null&&p.getBounds().containsChunk(x,z);File region=new File(new File(root,"region"),"r."+XFEarthBounds.chunkToRegion(x)+"."+XFEarthBounds.chunkToRegion(z)+".mca");msg(s,"Inside profile bounds: "+inside);msg(s,"Region file exists: "+region.isFile()+" (this does not prove that the specific chunk exists)");return;} throw new WrongUsageException(USAGE);
 }
 public static String[] getPackIds(){java.util.List<XFEarthMapPack> packs=new XFEarthMapRepository(new File(".")).discover();String[] ids=new String[packs.size()];for(int i=0;i<packs.size();i++)ids[i]=packs.get(i).manifest.id;return ids;}
 private static void msg(ICommandSender s,String m){s.addChatMessage(new ChatComponentText(m));}
}
