#!/usr/bin/env python3
"""Validate that every Xenofactions GUI command has complete English text."""
from __future__ import print_function

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src/main/java/com/hfr/xfgui/XFCommandCatalog.java"
LANG = ROOT / "src/main/resources/assets/hfr/lang/en_US.lang"


def catalog_ids(source):
    """Extract literal entries and IDs generated by the catalog's command arrays."""
    ids = re.findall(r'add\("([^"]+)",Category\.', source)
    for array_name, prefix in (("xcs", "xc_"), ("toggles", "xc_"), ("tdm", "tdm_")):
        match = re.search(r'String\[\]\s+' + array_name + r'=\{(.*?)\};', source, re.DOTALL)
        if match is None:
            raise AssertionError("Could not find catalog array: " + array_name)
        values = re.findall(r'"([^"]+)"', match.group(1))
        ids.extend(prefix + value.split("|", 1)[0] for value in values)
    return ids


def translations(source):
    values = {}
    duplicates = []
    for line_number, line in enumerate(source.splitlines(), 1):
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key in values:
            duplicates.append("%s (line %d)" % (key, line_number))
        values[key] = value
    return values, duplicates


def validate():
    ids = catalog_ids(CATALOG.read_text(encoding="utf-8"))
    if len(ids) != len(set(ids)):
        duplicates = sorted(command_id for command_id in set(ids) if ids.count(command_id) > 1)
        raise AssertionError("Duplicate catalog command IDs: " + ", ".join(duplicates))

    localized, duplicate_keys = translations(LANG.read_text(encoding="utf-8"))
    errors = []
    if duplicate_keys:
        errors.append("Duplicate English localization keys: " + ", ".join(duplicate_keys))
    for command_id in ids:
        for suffix in ("name", "desc"):
            key = "xf.command.%s.%s" % (command_id, suffix)
            value = localized.get(key)
            if value is None:
                errors.append("Missing " + key)
            elif not value.strip() or value.strip() == key:
                errors.append("Invalid value for " + key)
    for obsolete in ("xf.command.xc_.name", "xf.command.xc_.desc", "xf.command.tdm_.name", "xf.command.tdm_.desc"):
        if obsolete in localized:
            errors.append("Obsolete placeholder key remains: " + obsolete)
    if errors:
        raise AssertionError("\n".join(errors))
    return ids


if __name__ == "__main__":
    try:
        command_ids = validate()
    except AssertionError as error:
        print(error, file=sys.stderr)
        sys.exit(1)
    print("Validated name and description localization for %d Xenofactions GUI commands." % len(command_ids))
